### ISSUE TITLE
Unable to provide Service account json file to netlify server 

### ISSUE THREAD

**Issue by jaybharadia** [posva/nuxt--vuefire-example-blaze-plan#1]
In this below variable, what should I assign (  path ) ? 
https://github.com/posva/nuxt--vuefire-example-blaze-plan/blob/e51fbd3a963c928b8d8ba74889d8052bb4c51537/.github/workflows/firebase-hosting-merge.yml#L25

I have tried setting to `./service-account.json` path. Netlify server is unable to find that file.

### How to provide this `json` file to the server ?

**Comment by posva** [comment]
You need to provide the serialized JSON
