### ISSUE TITLE
Unable to display NuxtImg or NuxtPicture elements

### ISSUE THREAD

**Issue by crunchwrap89** [posva/nuxt--vuefire-example-blaze-plan#8]
HI,
When deploying the application as a serverless function with the blaze plan and nitro firebase preset, NuxtImg and NuxtPicture is not working.

I would be super happy if you could just give a hint of how to configure the app to allow that..
I could contribute with docs for it afterwards if you teach me.

P.S Thank you for a great repo.

**Comment by posva** [comment]
I don't think that part is related to VueFire or to this repository. You can still open a discussion on VueFire repo, maybe someone will help you out
